name: Bump Release
on:
  workflow_dispatch:
    inputs:
      create_release:
        type: boolean
        description: 'Create GitHub Release'
        required: false
        default: false



jobs:
  bump-main:
    if: "!contains(github.event.commits[0].message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.deploy-key }}

      - name: Get bumped version
        id: version
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --bumped-version
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Set version output
        id: set_version
        run: |
          NEXT_VERSION="v${{ steps.version.outputs.version }}"
          echo "Next version: $NEXT_VERSION"
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Generate full changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --tag ${{ steps.set_version.outputs.version }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --unreleased --tag ${{ steps.set_version.outputs.version }} --strip all
        env:
          OUTPUT: GITHUB_CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and tag release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): prepare for ${{ steps.set_version.outputs.version }}" || echo "No changes to commit"
          git tag -a ${{ steps.set_version.outputs.version }} -m "Release ${{ steps.set_version.outputs.version }}"
          git push
          git push origin tag ${{ steps.set_version.outputs.version }}
      
      - name: Upload github release
        uses: softprops/action-gh-release@v1
        if: inputs.create_release == true
        with:
           body_path: GITHUB_CHANGELOG.md
           tag_name: ${{ steps.set_version.outputs.version }}
